### ISSUE TITLE
catena4612_simple needs "Adafruit_Unified_Sensor"

### ISSUE THREAD

**Issue by sunburntcat** [mcci-catena/Catena-Sketches#116]
The Adafruit_BME280_Library seems to require the Adafruit Unified Sensor library. 

Installing it manually takes care of the error.

**Comment by terrillmoore** [comment]
Thanks, sorry. Actually, I should rename these libraries because we've diverged from upstream. But first things first.

**Comment by terrillmoore** [comment]
Hi team (@dhineshkumarmcci @svelmurugan92 @sjpark-mcci), can you please update the .dat file so that git-boot.sh works properly, and then file a PR? Please do a horizontal scan. Since the name of the library is ambiguous (ours or Adafruits?) and we want to make sure customers get the right repo, we should then start the somewhat lengthy/time-consuming process of renaming the remaining libraries to avoid ambiguity. We can discuss that process offline.

**Comment by dhineshkumarmcci** [comment]
Hi @terrillmoore , will do the needed changes and will submit a pull-request. Thanks!
